# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alien_vault_id', models.CharField(default=b'WSrO4uzhonxc', max_length=12)),
                ('address', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=255)),
            ],
        ),
    ]
