# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alien_vault_id', models.CharField(default=b'yfK7LbC61sY9', max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='visits',
            name='alien_vault_id',
        ),
        migrations.AddField(
            model_name='visits',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api_test.Users'),
            preserve_default=False,
        ),
    ]
