# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0004_auto_20180212_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alien_vault_id',
            field=models.CharField(default=b'r9OBAk0WtFSU', max_length=12, unique=True),
        ),
    ]
