# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 04:34
from __future__ import unicode_literals

import api_test.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0005_auto_20180212_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alien_vault_id',
            field=models.CharField(default=api_test.models.generate_id, max_length=12, unique=True),
        ),
    ]
